[package]
name = "ractor_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
ractor = "0.7.3"
tokio = { version = "1.25.0", features = ["full"] }
